services:
  vite-app:
    # Set the container name
    container_name: about-me-c

    # set name for the image
    image: about-me-i

    # Build the image using the Dockerfile in the current context
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev -- --host
