services:
  postgres-db:
    container_name: about-me-postgres-c

    image: postgres:17-alpine

    restart: always

    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: portfolio

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend-app:
    container_name: about-me-frontend-c

    image: about-me-frontend-i

    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    working_dir: /app

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run dev -- --host

  backend-app:
    container_name: about-me-backend-c

    image: about-me-backend-i

    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    working_dir: /app

    volumes:
      - ./backend:/app
      - /app/node_modules

    command: npm run dev

volumes:
  pgdata:
